name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy subfolder contents to root
        run: |
          cp -r public/* .
          # Add any build or processing steps if needed
          git add .
          git commit -m "Deploy"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
        env:
          CI: true
